### ISSUE TITLE
numpy UFuncNoLoopError

### ISSUE THREAD

**Issue by boswellp** [nlsfi/HASlib#4]
A small issue. For a Windows 10 install I had to change install_requires in setup.py to 'numpy==1.22.3'. Without this, numpy 1.22.2 was installed which threw the error :
numpy.core._exceptions._UFuncNoLoopError: ufunc 'lookup' did not contain a loop with signature matching types <class 'numpy.dtype[uint8]'> -> None 
This type of numpy error is apparently well-known.

**Comment by jorgegarciamateos** [comment]
I cannot install. When running 'python setup.py bdist_wheel' I get errors. Please, any help? Thanks. Jorge
running bdist_wheel
running build
running build_py
copying galileo_has_decoder/tcp_server.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/utils_sbf.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/ssr_formats.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/has_classes.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/ssr_converter.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/binex_reading.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/serial_reading.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/utils_testing.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/tcp_binex_reading.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/file_write.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/__init__.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/ssr_igs.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/utils.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/ssr_classes.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/writers.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/conv.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/ssr_rtcm.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/readers.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/crc.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/sbf_reading.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/tcp_sbf_reading.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/utils_binex.py -> build/lib/galileo_has_decoder
copying galileo_has_decoder/resources/genMatrix.txt -> build/lib/galileo_has_decoder/resources
/home/jorge/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
installing to build/bdist.linux-x86_64/wheel
running install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    setup(
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/command/bdist_wheel.py", line 445, in run
    self.run_command("install")
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 972, in run_command
    cmd_obj.ensure_finalized()
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in finalize_options
    super().finalize_options()
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 408, in finalize_options
    'dist_fullname': self.distribution.get_fullname(),
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
    return _distribution_fullname(self.get_name(), self.get_version())
  File "/home/jorge/.local/lib/python3.8/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
    canonicalize_version(version, strip_trailing_zero=False),
TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
